name: CI

on: [push, pull_request]

jobs:
  coding-style:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-12
            sh .ci/check-format.sh
      shell: bash
  make_test:
    runs-on: macOS
    steps:
      run: |
        brew install i686-elf-gcc
        brew install qemu
        make all